### ISSUE TITLE
Síntesis sobre la gestión de proyectos 

### ISSUE THREAD

**Issue by Jaci14** [SistemasTecTlaxiaco/sintesis-Jaci14#2]
[Sintesis gestion de proyectos - Jaciel Garcia Santaigo.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-Jaci14/files/7132261/Sintesis.gestion.de.proyectos.-.Jaciel.Garcia.Santaigo.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Excelente trabajo, considero que esta muy completo, identifica las ideas principales y los puntos claves.
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
